### ISSUE TITLE
Create new project mailing lists

### ISSUE THREAD

**Issue by wguttmn** [castor-data-binding/castor#1]
Create new project mailing lists, at least 

* ann
* dev
*user

**Comment by stepince** [comment]
HI Werner,
  Glad to see the project is alive. I have been using castor for a while. I use castor for xml marshalling/unmarshalling.  I was wondering if there was any interest in doing json marshalling/unmarshallng.

Steve

**Comment by wguttmn** [comment]
Sure. The question is how that should/could be added as a feature ....

**Comment by stepince** [comment]
Yes. I do like castor's xml mapping configuration and I think adding a json marshalling/unmarshalling would be a very valuable feature.

**Comment by wguttmn** [comment]
If that's the case, why don't you create a new ticket, stating your feature request and I'll be more than happy to join you. As this is github, feel free to clone the repo and send pull requests with ideas, additions, ....

**Comment by stepince** [comment]
Thx I will.

**Comment by wguttmn** [comment]
Created three new mailing lists at freelists.org and sent email to old Codehaus mailing lists highlighting this.
