### ISSUE TITLE
Code Generator for Types

### ISSUE THREAD

**Issue by AbrahamAlarcon** [castor-data-binding/castor#17]
Hi,
We were using castor 1.3.2 for auto-generating a soap web service client and found this problem.
In this version for Types you have replaced the static method "valueOf" by "fromValue", which is nicer from data perspective, however we found there is a problem with concurrent threads.

Here is an example of the current code auto generated:

    public static MyType fromValue(String value)
    {
        MyType c = (MyType)enumConstants.get(value);
        if(c != null)
            return c;
        else
            throw new IllegalArgumentException(value);
     }

As the method is static all the threads will access this method concurrently at unmarshalling step.
At the moment of one thread doing "if(c!=null)", another thread can change the reference of "c" in the line "MyType c = (MyType) enumConstants.get(value)".

We had the issue and after a lot of research identified this problem.
We have fixed this in the meantime adding a synchronized block (to avoid synchronize method)

    static final Object monitorObj = new Object();
    public static MyType fromValue(String value)
    {
		synchronized (monitorObj) {
			MyType c = (MyType) enumConstants.get(value);
			if(c != null)
				return c;
			else
				throw new IllegalArgumentException(value);
		}
    }

But obviously the idea is to help in improving this very useful framework,

Thanks,

**Comment by wguttmn** [comment]
Could you please attach a minimal test case (incl. XML schema, code generated, ...) for me to have an immediate starting point ?

**Comment by wguttmn** [comment]
More importantly, can I take it that you are using Java 5.0 or above ?

**Comment by wguttmn** [comment]
And you do realize that if you happen to generate Java 5.0 code from a <simpleType> declaration, those classes carry the default valueOf() methods ?

**Comment by AbrahamAlarcon** [comment]
Hi,
sorry for not replying before, but we were testing with multiple threads
and noted the issue is still there even after adding the synchronized
block. It improved but issue still continues.
We are researching and testing more but all indicates the problem with
Types is one level up.
We are using java 6 to generate the code, which generates fromValue()
instead of valueOf().
Back to you when our all tests pass and hope to find a better solution.
Thanks,


On Mon, Feb 22, 2016 at 6:48 AM, Werner Guttmann <notifications@github.com>
wrote:

> And you do realize that if you happen to generate Java 5.0 code from a
> declaration, those classes carry the default valueOf() methods ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/castor-data-binding/castor/issues/17#issuecomment-187098693>
> .
>



-- 
Abraham Alarcon
+56 9 63060197
abraham.alarcon@gmail.com

**Comment by wguttmn** [comment]
Please reopen when appropriate
