### ISSUE TITLE
Duplicate stax-api dependencies

### ISSUE THREAD

**Issue by awhitford** [castor-data-binding/castor#18]
Using `castor-xml-1.4.0`, I noticed that there is a duplicate `stax-api` dependency:

- org.codehaus.castor:castor-xml:jar:1.4.0 (compile) Information
 - org.codehaus.castor:castor-core:jar:1.4.0 (compile) Information
 - commons-lang:commons-lang:jar:2.6 (compile) Information
 - stax:stax:jar:1.2.0 (compile) Information
   - stax:stax-api:jar:1.0.1 (compile) Information
 - javax.xml.stream:stax-api:jar:1.0-2 (compile) Information

One should prevail.  Not against the last one.

**Comment by awhitford** [comment]
Note that `stax:stax-api:1.0.1` is the dependency for `org.apache.xmlbeans:xmlbeans:jar:2.6.0` which is a dependency for `org.apache.poi:poi-ooxml:jar:3.13`...  So, `stax:stax-api` is popular.

**Comment by wguttmn** [comment]
Yes, popularity is a problem here, given that the javax.* dependency should be the one to be used.

**Comment by wguttmn** [comment]
What Java version are you on, iima ?

**Comment by awhitford** [comment]
Don't think Java version is that relevant, but I am generally using Java 8.

**Comment by awhitford** [comment]
Wait, are you thinking that I can declare `stax` as `provided`?

**Comment by wguttmn** [comment]
Well, it might not be that easy. As you are on Java 8, the STaX API is part of the JRE/JDK anyhow (though with javax.xml. prefices). This happened with Java 6, as far as I remember. For those still on Java 5 (and there's some ;-)), this won't be the case, hence they'll need the stax-api and a corresponding implementation. I still need to get my head around this fully.

**Comment by wguttmn** [comment]
But you can definitely <exclude> STAX on your side, that should solve things in the short run.

**Comment by awhitford** [comment]
If STAX is built in since Java 6, why not simply drop the declaration, documenting the fact that pre-Java 6, one needs to add the stax implementation dependency?  I assert that, these days, Java 6+ is the norm, while pre-Java 6 is the exception.  (Never mind that prior to Java 8 is EOL.)

**Comment by wguttmn** [comment]
Yes, that would be an option ;-). One might actually be able to do so via Maven dependencies as well.

**Comment by awhitford** [comment]
It appears that the build is configured for Java 7 compliance, so it doesn't look like one needs to worry about pre-Java6 compliance anymore.

**Comment by awhitford** [comment]
I think this is done...
