### ISSUE TITLE
Fix broken reference guide links for single HTML and PDF

### ISSUE THREAD

**Issue by wguttmn** [castor-data-binding/castor#2]
Fix broken reference guide links for single HTML and PDF

**Comment by kazuki43zoo** [comment]
And links to access each Project Modules are broken in [top page](http://castor-data-binding.github.io/castor/).

**Comment by wguttmn** [comment]
Hi,

the links should now be fixed, and I've fixed the links to the 1.3.3 
reference guides as well.

Werner

On 06.05.2015 18:37, Kazuki Shimizu wrote:
> And links to access each Project Modules are broken in top page
> <http://castor-data-binding.github.io/castor/>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/castor-data-binding/castor/issues/2#issuecomment-99531756>.
>

---
This email is free from viruses and malware because avast! Antivirus protection is active.
http://www.avast.com
