### ISSUE TITLE
Missing tag for 1.4.1

### ISSUE THREAD

**Issue by wltjr** [castor-data-binding/castor#64]
Minor issue, but there does not seem to be a tag/release for 1.4.1. Though it does exist in maven, and sources show 1.4.2. Can a 1.4.1 tag/release be created? Thanks!

**Comment by wltjr** [comment]
Can someone please create a tag for 1.4.1? Should not take long, much appreciated!!!

**Comment by wltjr** [comment]
@wguttmn @awhitford tag please!!! I can fork and tag but rather not. 1.4.1 is published on maven, etc. There should be a official source like 1.4.0 release on github. Thank you!!!!

**Comment by wguttmn** [comment]
Done. There’s now a 1.4.1 tag.

**Comment by wltjr** [comment]
Thank you very much!

**Comment by wguttmn** [comment]
Btw, I might be convinced to assist in shipping a 1.4.2 release should there be a need and some good CRs.
